baseURL = "https://autoscuolasilveri.it/"
languageCode = "it_IT"
defaultContentLanguage = "it"
title = "Autoscuola Silveri"
copyright = "Copyright @ {year} AUTOSCUOLA SILVERI P.Iva: 01164690446. Tutti i diritti riservati."

enableRobotsTXT = true
canonifyURLs = true

# Ionicons Icon font - https://ionicons.com/v2/

[menu]
    [[menu.nav]]
        name    = "Chi siamo"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Servizi"
        url     = "/service"
        weight  = 3
    # [[menu.nav]]
    #     name    = "Galleria"
    #     url     = "/gallery"
    #     weight  = 4
    [[menu.nav]]
        name    = "Novità"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contatti"
        url     = "/contact"
        weight  = 6

[params]
    home = "HOME"
    dateFormat = "02-01-2006"
    logo = "images/logo.png"
    logo_alt = "Autoscuola Silveri"

    [params.banner]
        enable = true
        bgImage = "images/comunanza.jpg"
        heading = "AUTOSCUOLA SILVERI"
        description = "DA PIù DI 50 ANNI UN UNICA MISSIONE: INSEGNARE A GUIDARE CON DIVERTIMENTO ED IN SICUREZZA"
        btn     = true
        btnText = "Contattaci"
        btnURL  = "/contact"
        [[params.banner.flipText]]
            title   = "PATENTI"
        [[params.banner.flipText]]
            title   = "ASSICURAZIONI"
        [[params.banner.flipText]]
            title   = "PRATICHE AUTO"

    [params.about]
        enable = true
        title   = "CHI SIAMO"
        content = """Dal 1967 assistiamo i nostri studenti nel loro obiettivo: guidare.
                    <br><br>Combinando i valori tradizionali con lo stile moderno, siamo diventati una delle principali scuole guida nell'entroterra marchigiano con oltre 50 anni di esperienza nella seconda generazione.
                    <br><br>I nostri istruttori professionali, affidabili e amichevoli renderanno l'apprendimento nel guidare il più semplice possibile e ti faranno sentire al sicuro al volante.
                    <br><br>Non vediamo l'ora di accompagnarti in questo percorso e siamo sempre disponibili per rispondere alle tue domande!"""
        image   = "images/logo.png"

    [params.cta]
        enable = true
        title   = "TI ASPETTIAMO!"
        content = "Clicca qua sotto per contattarci! Vieni a trovarci in una delle sedi o inviaci un messaggio!"
        btnText = "Contattaci"
        btnURL  = "/contact"

    [params.maintenance]
        enable = false
        image = "images/maintenance.png"

    [params.associates]
        enable = true

    [params.feature]
        enable = true

    [params.team]
        enable = true

    [params.service]
        enable = true

        
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false